services:
  - type: web
    name: daily2odds
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node build
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 3000
    healthCheckPath: /