services:
  - type: web
    name: daily2odds
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true