services:
  - type: web
    name: daily2odds
    env: node
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true